[package]
name = "zk_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.6"
serde = { version="1.0.163", features=["derive"] }
serde_json = "1.0.96"
sha3 = "0.10.8"
rand = "0.8.5"
